name: test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - anyio=4.10.0
  - arrow-cpp=21.0.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - datasets=4.4.1
  - dill=0.4.0
  - exceptiongroup=1.3.0
  - expat=2.7.3
  - filelock=3.20.0
  - frozenlist=1.8.0
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - h11=0.16.0
  - h5py=3.15.1
  - hdf5=1.14.5
  - hf-xet=1.1.8
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jansson=2.14
  - ld_impl_linux-64=2.44
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.3.2
  - multidict=6.7.0
  - multiprocess=0.70.18
  - ncurses=6.5
  - numexpr=2.14.1
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.3
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - s2n=1.5.14
  - safetensors=0.6.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - distro==1.9.0
      - fsspec==2025.12.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - openai==2.9.0
      - opencv-python-headless==4.8.1.78
      - pillow==12.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - torch==2.1.0+cu118
      - torchaudio==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - transformers==4.32.0
      - triton==2.1.0
      - typing-inspection==0.4.2
prefix: /home/zhuxuzhou/miniconda3/envs/test
